# Generated by Django 3.2.12 on 2022-09-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cow',
            old_name='SensorID_id',
            new_name='sensorID',
        ),
    ]
