# Generated by Django 3.2.12 on 2022-09-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0002_rename_sensorid_id_cow_sensorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cow',
            old_name='sensorID',
            new_name='sensorID_id',
        ),
    ]
