# Generated by Django 3.2.12 on 2022-09-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0003_rename_sensorid_cow_sensorid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cow',
            old_name='sensorID_id',
            new_name='SensorID_id',
        ),
    ]
