# Generated by Django 3.2.12 on 2022-09-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0004_rename_sensorid_id_cow_sensorid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
