# Generated by Django 3.2.12 on 2022-09-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0006_alter_cow_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
