# Generated by Django 3.2.12 on 2022-09-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0011_remove_cow_pregnancy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='pregnancy_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
